In [274]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder

%matplotlib inline  
## With this the graph appears directly below the cell in a proper way

In [275]:
df=pd.read_csv("./Datasets/Flight-Price/Clean_Dataset.csv")

In [276]:
data1=pd.read_csv("./Datasets/Flight-Price/business.csv")
data2=pd.read_csv("./Datasets/Flight-Price/economy.csv")

In [277]:
print(df.info())
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB
None
(300153, 12)

In [278]:
df.describe()

          Unnamed: 0       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

In [279]:
df.head()

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [280]:
print(data1.head(2))
print(data1.info())

         date    airline ch_code  num_code dep_time   from time_taken  \
0  11-02-2022  Air India      AI       868    18:00  Delhi    02h 00m
1  11-02-2022  Air India      AI       624    19:00  Delhi    02h 15m

        stop arr_time      to   price
0  non-stop     20:00  Mumbai  25,612
1  non-stop     21:15  Mumbai  25,612
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        93487 non-null  object
 1   airline     93487 non-null  object
 2   ch_code     93487 non-null  object
 3   num_code    93487 non-null  int64
 4   dep_time    93487 non-null  object
 5   from        93487 non-null  object
 6   time_taken  93487 non-null  object
 7   stop        93487 non-null  object
 8   arr_time    93487 non-null  object
 9   to          93487 non-null  object
 10  price       93487 non-null  object
dtypes: int64(1), object(10)
memory usage: 7.8+ MB
None

## Feature Engineering

In [281]:
data1["Date"]=data1["date"].str.split('-').str[0]
data1["Month"]=data1["date"].str.split('-').str[1] 
data1["Year"]=data1["date"].str.split('-').str[2] 
## with the help of this we have splitted the date in a single column

In [282]:
data1.head(2)
data1.info()  ## Here we can see that after seprating the dates they are still in object type so now we'll convert this in to integer

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        93487 non-null  object
 1   airline     93487 non-null  object
 2   ch_code     93487 non-null  object
 3   num_code    93487 non-null  int64
 4   dep_time    93487 non-null  object
 5   from        93487 non-null  object
 6   time_taken  93487 non-null  object
 7   stop        93487 non-null  object
 8   arr_time    93487 non-null  object
 9   to          93487 non-null  object
 10  price       93487 non-null  object
 11  Date        93487 non-null  object
 12  Month       93487 non-null  object
 13  Year        93487 non-null  object
dtypes: int64(1), object(13)
memory usage: 10.0+ MB

In [283]:
data1["Date"]=data1["Date"].astype(int)
data1["Month"]=data1["Month"].astype(int)
data1["Year"]=data1["Year"].astype(int)

In [284]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        93487 non-null  object
 1   airline     93487 non-null  object
 2   ch_code     93487 non-null  object
 3   num_code    93487 non-null  int64
 4   dep_time    93487 non-null  object
 5   from        93487 non-null  object
 6   time_taken  93487 non-null  object
 7   stop        93487 non-null  object
 8   arr_time    93487 non-null  object
 9   to          93487 non-null  object
 10  price       93487 non-null  object
 11  Date        93487 non-null  int64
 12  Month       93487 non-null  int64
 13  Year        93487 non-null  int64
dtypes: int64(4), object(10)
memory usage: 10.0+ MB

In [285]:
data1=data1.drop('date',axis=1)

In [286]:
data1.head(2)

,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,Date,Month,Year
0,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612",11,2,2022
1,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612",11,2,2022

In [287]:
data1['Arrival_hour']=data1["arr_time"].str.split(':').str[0]
data1['Arrival_min']=data1["arr_time"].str.split(':').str[1]
data1['Arrival_hour']=data1['Arrival_hour'].astype(int)
data1['Arrival_min']=data1['Arrival_min'].astype(int)
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   airline       93487 non-null  object
 1   ch_code       93487 non-null  object
 2   num_code      93487 non-null  int64
 3   dep_time      93487 non-null  object
 4   from          93487 non-null  object
 5   time_taken    93487 non-null  object
 6   stop          93487 non-null  object
 7   arr_time      93487 non-null  object
 8   to            93487 non-null  object
 9   price         93487 non-null  object
 10  Date          93487 non-null  int64
 11  Month         93487 non-null  int64
 12  Year          93487 non-null  int64
 13  Arrival_hour  93487 non-null  int64
 14  Arrival_min   93487 non-null  int64
dtypes: int64(6), object(9)
memory usage: 10.7+ MB

In [288]:
data1=data1.drop("arr_time",axis=1)

In [289]:
data1.head(2)

,airline,ch_code,num_code,dep_time,from,time_taken,stop,to,price,Date,Month,Year,Arrival_hour,Arrival_min
0,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,Mumbai,"25,612",11,2,2022,20,0
1,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,Mumbai,"25,612",11,2,2022,21,15

In [290]:
data1['Departure_hour']=data1["dep_time"].str.split(':').str[0]
data1['Departure_min']=data1["dep_time"].str.split(':').str[1]
data1['Departure_hour']=data1['Departure_hour'].astype(int)
data1['Departure_min']=data1['Departure_min'].astype(int)
data1=data1.drop("dep_time",axis=1)
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   airline         93487 non-null  object
 1   ch_code         93487 non-null  object
 2   num_code        93487 non-null  int64
 3   from            93487 non-null  object
 4   time_taken      93487 non-null  object
 5   stop            93487 non-null  object
 6   to              93487 non-null  object
 7   price           93487 non-null  object
 8   Date            93487 non-null  int64
 9   Month           93487 non-null  int64
 10  Year            93487 non-null  int64
 11  Arrival_hour    93487 non-null  int64
 12  Arrival_min     93487 non-null  int64
 13  Departure_hour  93487 non-null  int64
 14  Departure_min   93487 non-null  int64
dtypes: int64(8), object(7)
memory usage: 10.7+ MB

In [291]:
data1.head(2)

,airline,ch_code,num_code,from,time_taken,stop,to,price,Date,Month,Year,Arrival_hour,Arrival_min,Departure_hour,Departure_min
0,Air India,AI,868,Delhi,02h 00m,non-stop,Mumbai,"25,612",11,2,2022,20,0,18,0
1,Air India,AI,624,Delhi,02h 15m,non-stop,Mumbai,"25,612",11,2,2022,21,15,19,0

In [292]:
data1["stop"].unique()   ## in this dataset the values were very odd so i did this to make this into a valuable feature
data1["stop"]=data1["stop"].str.split('-').str[0]
data1.head(3)

,airline,ch_code,num_code,from,time_taken,stop,to,price,Date,Month,Year,Arrival_hour,Arrival_min,Departure_hour,Departure_min
0,Air India,AI,868,Delhi,02h 00m,non,Mumbai,"25,612",11,2,2022,20,0,18,0
1,Air India,AI,624,Delhi,02h 15m,non,Mumbai,"25,612",11,2,2022,21,15,19,0
2,Air India,AI,531,Delhi,24h 45m,1,Mumbai,"42,220",11,2,2022,20,45,20,0

In [293]:
data1["stop"].unique()

array(['non', '1', '2+'], dtype=object)

In [294]:
data1["stop"]=data1["stop"].map({'non':0,'1':1,'2+':2})
data1.head(2)

,airline,ch_code,num_code,from,time_taken,stop,to,price,Date,Month,Year,Arrival_hour,Arrival_min,Departure_hour,Departure_min
0,Air India,AI,868,Delhi,02h 00m,0,Mumbai,"25,612",11,2,2022,20,0,18,0
1,Air India,AI,624,Delhi,02h 15m,0,Mumbai,"25,612",11,2,2022,21,15,19,0

In [295]:
data2.head(2)   ## now to work on time_taken Feature i am going to use this dataset4

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
0,11-02-2022,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953"
1,11-02-2022,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953"

In [296]:
data2["Time_taken(hrs)"]=data2["time_taken"].str.split(' ').str[0].str.split('h').str[0]
# data2["Time_taken(hrs)"]=data2["Time_taken(hrs)"].astype(int)
data2["Time_taken(hrs)"].unique()

array(['02', '12', '16', '11', '14', '15', '03', '05', '08', '06', '18',
       '23', '24', '04', '19', '22', '26', '17', '20', '21', '07', '10',
       '28', '09', '13', '29', '27', '30', '25', '31', '33', '36', '35',
       '34', '39', '01', '37', '40', '32', '7', '41', '38', '1.03',
       '1.02', '2', '00', '47', '1.01', '5', '42', '49', '45', '44'],
      dtype=object)

In [297]:
mask=data2["Time_taken(hrs)"].str.contains(r"\.", na=False)    ## there were some decimal values in the dataset that's why did this type of split in there so we can get the whole Hour value for our new column
data2.loc[mask,"Time_taken(hrs)"]=(data2.loc[mask,"Time_taken(hrs)"].str.split('.').str[0])

In [298]:
data2["Time_taken(hrs)"].unique()
data2["Time_taken(hrs)"]=data2["Time_taken(hrs)"].astype(int)

In [299]:
data2.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,Time_taken(hrs)
0,11-02-2022,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953",2
1,11-02-2022,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953",2
2,11-02-2022,AirAsia,I5,764,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956",2
3,11-02-2022,Vistara,UK,995,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955",2
4,11-02-2022,Vistara,UK,963,08:50,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955",2

In [300]:
data2["Time_taken(min)"]=data2["time_taken"].str.split(' ').str[1].str.split('m').str[0]

In [301]:
data2["Time_taken(min)"].unique()

array(['10', '20', '15', '05', '45', '30', '40', '50', '00', '25', '35',
       '55', '04', '', '59', '24'], dtype=object)

In [302]:
mask = data2["Time_taken(min)"] == ''  ## these are the values which happen because of these 4 values which were with the wrong entry in the data in time_taken Column (like this 1.03h m)

In [303]:
data2.loc[mask, "Time_taken(min)"] = (data2.loc[mask, "time_taken"]
    .str.extract(r'\.(\d+)')[0])

In [304]:
data2["Time_taken(min)"]=data2["Time_taken(min)"].astype(int)
data2["Time_taken(min)"].unique()

array([10, 20, 15,  5, 45, 30, 40, 50,  0, 25, 35, 55,  4,  3,  2, 59,  1,
       24])

In [305]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 13 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   date             206774 non-null  object
 1   airline          206774 non-null  object
 2   ch_code          206774 non-null  object
 3   num_code         206774 non-null  int64
 4   dep_time         206774 non-null  object
 5   from             206774 non-null  object
 6   time_taken       206774 non-null  object
 7   stop             206774 non-null  object
 8   arr_time         206774 non-null  object
 9   to               206774 non-null  object
 10  price            206774 non-null  object
 11  Time_taken(hrs)  206774 non-null  int64
 12  Time_taken(min)  206774 non-null  int64
dtypes: int64(3), object(10)
memory usage: 20.5+ MB

In [306]:
data2=data2.drop("time_taken",axis=1)

In [307]:
data2.head(2)

,date,airline,ch_code,num_code,dep_time,from,stop,arr_time,to,price,Time_taken(hrs),Time_taken(min)
0,11-02-2022,SpiceJet,SG,8709,18:55,Delhi,non-stop,21:05,Mumbai,"5,953",2,10
1,11-02-2022,SpiceJet,SG,8157,06:20,Delhi,non-stop,08:40,Mumbai,"5,953",2,20

## Now we'll work in the Catogorical Features (we'll use One Hot Encoding here and make a separate Dataframe from this and after that we'll merge that into the main dataset and remove the old Columns  (We'll do this in Data1)

In [308]:
encoder=OneHotEncoder()
data1.head(2)

,airline,ch_code,num_code,from,time_taken,stop,to,price,Date,Month,Year,Arrival_hour,Arrival_min,Departure_hour,Departure_min
0,Air India,AI,868,Delhi,02h 00m,0,Mumbai,"25,612",11,2,2022,20,0,18,0
1,Air India,AI,624,Delhi,02h 15m,0,Mumbai,"25,612",11,2,2022,21,15,19,0

In [309]:
encoder.fit_transform(data1[["airline","from","to"]]).toarray()

array([[1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.]], shape=(93487, 14))

In [310]:
encoded_df=pd.DataFrame(encoder.fit_transform(data1[["airline","from","to"]]).toarray(),columns=encoder.get_feature_names_out())
encoded_df

,airline_Air India,airline_Vistara,from_Bangalore,from_Chennai,from_Delhi,from_Hyderabad,from_Kolkata,from_Mumbai,to_Bangalore,to_Chennai,to_Delhi,to_Hyderabad,to_Kolkata,to_Mumbai
0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93482,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
93483,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
93484,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
93485,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
93486,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [313]:
data1=pd.concat([data1,encoded_df],axis=1)

In [316]:
data1.head()

,airline,ch_code,num_code,from,time_taken,stop,to,price,Date,Month,...,from_Delhi,from_Hyderabad,from_Kolkata,from_Mumbai,to_Bangalore,to_Chennai,to_Delhi,to_Hyderabad,to_Kolkata,to_Mumbai
0,Air India,AI,868.0,Delhi,02h 00m,0.0,Mumbai,"25,612",11.0,2.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Air India,AI,624.0,Delhi,02h 15m,0.0,Mumbai,"25,612",11.0,2.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,Air India,AI,531.0,Delhi,24h 45m,1.0,Mumbai,"42,220",11.0,2.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,Air India,AI,839.0,Delhi,26h 30m,1.0,Mumbai,"44,450",11.0,2.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,Air India,AI,544.0,Delhi,06h 40m,1.0,Mumbai,"46,690",11.0,2.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0